import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
     
      <div className="flex min-h-screen bg-white ">
   
        <SideBar/>
        <div className="w-full">
        <Header/>
        {children}
        </div>
        </div>
        </body>
        
    
    </html>
  );
}
