export type Languages = Record<"name" | "country" , string>;
export const languages = [
    { name: "Mandarin Chinese", country: "China" },
    { name: "Spanish", country: "Spain" },
    { name: "English", country: "United Kingdom" },
    { name: "Hindi", country: "India" },
    { name: "Bengali", country: "Bangladesh" },
    { name: "Portuguese", country: "Portugal" },
    { name: "Russian", country: "Russia" },
    { name: "Japanese", country: "Japan" },
    { name: "Western Punjabi", country: "Pakistan" },
    { name: "Marathi", country: "India" },
    { name: "Telugu", country: "India" },
    { name: "Wu Chinese", country: "China" },
    { name: "Turkish", country: "Turkey" },
    { name: "Korean", country: "South Korea" },
    { name: "French", country: "France" },
    { name: "German", country: "Germany" },
    { name: "Vietnamese", country: "Vietnam" },
    { name: "Tamil", country: "India" },
    { name: "Yue Chinese", country: "China" },
    { name: "Urdu", country: "Pakistan" },
    { name: "Javanese", country: "Indonesia" },
    { name: "Italian", country: "Italy" },
    { name: "Egyptian Arabic", country: "Egypt" },
    { name: "Gujarati", country: "India" },
    { name: "Iranian Persian", country: "Iran" },
    { name: "Bhojpuri", country: "India" },
    { name: "Min Nan Chinese", country: "China" },
    { name: "Hakka Chinese", country: "China" },
    { name: "Jin Chinese", country: "China" },
    { name: "Hausa", country: "Nigeria" },
  ] as Languages[]